---
- name: Ensure required Traefik directories are created
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - { path: "{{ traefik_config_dir }}",         owner: root,    group: root }
    - { path: "{{ traefik_config_dynamic_dir }}", owner: root,    group: root }
    - { path: "{{ traefik_logs_dir }}",           owner: traefik, group: traefik }

- name: Ensure Traefik static configuration is applied
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ traefik_config_static_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Ensure Traefik ingress routes configuration is applied
  ansible.builtin.template:
    src: route.yaml.j2
    dest: "{{ traefik_config_dynamic_dir }}/route-{{ route.name }}.yaml"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ traefik_ingress_routes }}"
  loop_control:
    loop_var: route

- name: Ensure Traefik middlewares configuration is applied
  ansible.builtin.template:
    src: middleware.yaml.j2
    dest: "{{ traefik_config_dynamic_dir }}/middleware-{{ middleware.name }}.yaml"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ traefik_middlewares }}"
  loop_control:
    loop_var: middleware
