---
- name: Ensure Traefik service unit is applied
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: '0644'

- name: Ensure Traefik service is enabled and started
  ansible.builtin.systemd:
    name: traefik.service
    state: started
    enabled: true
    daemon_reload: true
