FROM docker.io/almalinux:8

RUN dnf install -y systemd procps-ng iproute util-linux python3 sudo epel-release hostname dnf-plugins-core \
    && dnf config-manager --set-enabled powertools -y \
    && dnf clean all \
    && rm -rf /var/cache/dnf/*

RUN truncate -s0 /etc/machine-id

STOPSIGNAL SIGRTMIN+3

CMD [ "/sbin/init" ]
