---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
driver:
  name: podman
platforms:
  - name: fedora37
    image: fedora:37-ansible
    dockerfile: ../Dockerfile.fedora37
    command: /sbin/init
    systemd: always
  - name: fedora36
    image: fedora:36-ansible
    dockerfile: ../Dockerfile.fedora36
    command: /sbin/init
    systemd: always
  - name: el9
    image: almalinux:9-ansible
    dockerfile: ../Dockerfile.el9
    command: /sbin/init
    systemd: always
  - name: el8
    image: almalinux:8-ansible
    dockerfile: ../Dockerfile.el8
    command: /sbin/init
    systemd: always
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer, yaml
  ssh_connection:
    pipelining: true
verifier:
  name: ansible
lint: |
    set -e
    yamllint .
    ansible-lint .
